export const data = [
	{
		key: "1",
		division: "John Brown",
		parentDivision: "División general",
		numCollaborators: 2,
		level: 2,
		numSubdivisions: 4,
		ambassador: "John Brown",
	},
	{
		key: "2",
		division: "Jim Green",
		parentDivision: "Productos",
		numCollaborators: 4,
		level: 1,
		numSubdivisions: 4,
		ambassador: "Aohn Brown",
	},
	{
		key: "3",
		division: "Joe Black",
		parentDivision: "I dunno",
		numCollaborators: 5,
		level: 3,
		numSubdivisions: 4,
		ambassador: "Bohn Brown",
	},
	{
		key: "4",
		division: "Jim Red",
		parentDivision: "Something else",
		numCollaborators: 1,
		level: 4,
		numSubdivisions: 4,
		ambassador: "Cohn Brown",
	},
	{
		key: "5",
		division: "Jim Red",
		parentDivision: "Something else",
		numCollaborators: 1,
		level: 4,
		numSubdivisions: 4,
		ambassador: "Cohn Brown",
	},
	{
		key: "6",
		division: "Jim Red",
		parentDivision: "Something else",
		numCollaborators: 1,
		level: 4,
		numSubdivisions: 4,
		ambassador: "Cohn Brown",
	},
	{
		key: "7",
		division: "Jim Red",
		parentDivision: "Something else",
		numCollaborators: 1,
		level: 4,
		numSubdivisions: 4,
		ambassador: "Cohn Brown",
	},
	{
		key: "8",
		division: "Jim Red",
		parentDivision: "Something else",
		numCollaborators: 1,
		level: 4,
		numSubdivisions: 4,
		ambassador: "Cohn Brown",
	},
	{
		key: "9",
		division: "Jim Red",
		parentDivision: "Something else",
		numCollaborators: 1,
		level: 4,
		numSubdivisions: 4,
		ambassador: "Cohn Brown",
	},
	{
		key: "10",
		division: "Jim Red",
		parentDivision: "Something else",
		numCollaborators: 1,
		level: 4,
		numSubdivisions: 4,
		ambassador: "Cohn Brown",
	},
];

